---

- name: Generic Router Configuration
  hosts: routers
  gather_facts: false
  connection: local

  
  tasks:
    - name: show commands
      ios_command:
        commands:
          - show ip int brief
      register: config

    - name: save output to local directory
      copy:
        content: "{{ config.stdout | replace('\\n', '\n') }}"
        dest: "CONFIGS/{{ inventory_hostname }}.ios"


#print output to screen
    - debug:
        var: config.stdout_lines 


    - name: ping test
      ios_ping:
        vrf: MGMT  
        dest: 10.199.199.1        


# add a new username
    - name: push config file
      ios_config:
        src: "/home/mark/automation/ansible/CONFIGS/test.txt"


    - pause:


#remove the username with a differnet module
    - name: remove username with ios_user module
      ios_user: 
        name: mark
        state: absent


